#ifndef STATSD_GEARMAND_MONITOR_H
#define STATSD_GEARMAND_MONITOR_H


#define GEARMAND_DEFAULT_PORT 4730
#define GEARMAND_DEFAULT_HOST "127.0.0.1"

#define STATSD_DEFAULT_PORT 8125
#define STATSD_DEFAULT_HOST  "127.0.0.1"

#define DEFAULT_SAMPLE_RATE 1.0

#define DEFAULT_POLLING_INTERVAL 2

#define VERSION "0.1"

#endif /* !STATSD_GEARMAND_MONITOR_H */